In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Specify the path to your CSV file
csv_file = 'results_scores/scores_test_mnist_tetro.csv'
df = pd.read_csv(csv_file)
df = df.drop(["run_name", "max_iters"], axis=1)

In [3]:
df.head()

,dataset,model_type,readout_type,num_layers,extension,loss,iou,acc,loss_foreground,iou_foreground,acc_foreground
0,mnist,cornn_model2,mean_time,16,1,0.155943,0.893486,0.942101,1.163495,0.459493,0.571493
1,mnist,cornn_model2,max_time,16,1,0.203852,0.854802,0.919819,1.532727,0.306960,0.416585
2,mnist,cornn_model2,fft,16,1,0.084844,0.944797,0.970739,0.634949,0.696490,0.790904
3,mnist,cornn_model2,last,16,1,0.190265,0.865763,0.926200,1.431079,0.342051,0.456508
4,mnist,cornn_model2,linear,16,1,0.026198,0.984205,0.991697,0.195291,0.907862,0.939604

In [4]:
# Define the grouping keys
group_keys = ["dataset", "model_type", "num_layers", "readout_type"]

# Define the metrics for which statistics should be computed
metrics = ["acc", "acc_foreground", "iou", "iou_foreground", "loss", "loss_foreground"]

# Group by the specified keys and compute statistics across the "extension" category
grouped_df = df.groupby(group_keys).agg({
    metric: ['median', 'min', 'max'] for metric in metrics
}).reset_index()

In [5]:
grouped_df

            dataset          model_type num_layers readout_type       acc  \
                                                                   median
0             mnist  baseline1_flexible          2       linear  0.887748
1             mnist  baseline1_flexible          4       linear  0.899076
2             mnist  baseline1_flexible          8       linear  0.928060
3             mnist  baseline1_flexible         16       linear  0.972720
4             mnist  baseline1_flexible         32       linear  0.867376
5             mnist     conv_recurrent2         16          fft  0.974344
6             mnist     conv_recurrent2         16         last  0.917567
7             mnist     conv_recurrent2         16       linear  0.983895
8             mnist     conv_recurrent2         16     max_time  0.922649
9             mnist     conv_recurrent2         16    mean_time  0.922605
10            mnist        cornn_model2         16          fft  0.968943
11            mnist        cornn_model2         16         last  0.935317
12            mnist        cornn_model2         16       linear  0.986542
13            mnist        cornn_model2         16     max_time  0.925939
14            mnist        cornn_model2         16    mean_time  0.926018
15  new_tetronimoes  baseline1_flexible          2       linear  0.893084
16  new_tetronimoes  baseline1_flexible          4       linear  0.911918
17  new_tetronimoes  baseline1_flexible          8       linear  0.972206
18  new_tetronimoes  baseline1_flexible         16       linear  0.855584
19  new_tetronimoes  baseline1_flexible         32       linear  0.855584
20  new_tetronimoes     conv_recurrent2         16          fft  0.993431
21  new_tetronimoes     conv_recurrent2         16         last  0.975093
22  new_tetronimoes     conv_recurrent2         16       linear  0.995471
23  new_tetronimoes     conv_recurrent2         16     max_time  0.936548
24  new_tetronimoes     conv_recurrent2         16    mean_time  0.951930
25  new_tetronimoes        cornn_model2         16          fft  0.997038
26  new_tetronimoes        cornn_model2         16         last  0.993886
27  new_tetronimoes        cornn_model2         16       linear  0.997418
28  new_tetronimoes        cornn_model2         16     max_time  0.986642
29  new_tetronimoes        cornn_model2         16    mean_time  0.989074

                       acc_foreground                      ...       iou  \
         min       max         median       min       max  ...       max
0   0.867376  0.888624       0.167325  0.000000  0.175360  ...  0.802627
1   0.867376  0.903130       0.252035  0.000000  0.282722  ...  0.826121
2   0.867376  0.930922       0.465001  0.000000  0.488726  ...  0.873249
3   0.867376  0.977157       0.810607  0.000000  0.833224  ...  0.956573
4   0.867376  0.987082       0.000000  0.000000  0.906093  ...  0.975419
5   0.867376  0.984425       0.812225  0.000000  0.885526  ...  0.970291
6   0.867376  0.942890       0.398685  0.000000  0.582316  ...  0.894683
7   0.867376  0.989762       0.883177  0.000000  0.925005  ...  0.980460
8   0.908388  0.928812       0.435984  0.320290  0.474936  ...  0.870382
9   0.898621  0.936211       0.430604  0.267267  0.533804  ...  0.883080
10  0.951163  0.976943       0.775031  0.647814  0.835254  ...  0.956369
11  0.911316  0.947356       0.524660  0.345154  0.614334  ...  0.902663
12  0.980632  0.991697       0.901748  0.858823  0.939604  ...  0.984205
13  0.918815  0.944388       0.455255  0.411114  0.588908  ...  0.897361
14  0.911441  0.942101       0.456219  0.340264  0.571493  ...  0.893486
15  0.855584  0.893240       0.263412  0.000000  0.264227  ...  0.811122
16  0.855584  0.912862       0.394114  0.000000  0.402098  ...  0.842710
17  0.855584  0.974733       0.815611  0.000000  0.830295  ...  0.951286
18  0.855584  0.999781       0.000000  0.000000  0.998711  ...  0.999570
19  0.855584  0.999824       0.000000  0.000000  0.998848  ...  0.999656
20  0.975504  0.995757       0.965574  0.843169  0.978538  ...  0.991751
21  0.855584  0.986217       0.835806  0.000000  0.917751  ...  0.973207
22  0.986845  0.996327       0.977153  0.922943  0.981354  ...  0.992833
23  0.855584  0.992072       0.568981  0.000000  0.957148  ...  0.984631
24  0.855584  0.992849       0.675580  0.000000  0.960767  ...  0.986316
25  0.994583  0.998231       0.984935  0.971896  0.990969  ...  0.996547
26  0.970125  0.996557       0.968162  0.814525  0.982680  ...  0.993381
27  0.995895  0.998410       0.986924  0.979386  0.991914  ...  0.996899
28  0.951164  0.997126       0.920335  0.685429  0.985604  ...  0.994488
29  0.966247  0.998252       0.935900  0.776540  0.991209  ...  0.996588

   iou_foreground                          loss                      \
           median       min       max    median       min       max
0        0.104304  0.000000  0.122193  0.292788  0.291803  0.695460
1        0.167925  0.000000  0.183224  0.265969  0.256048  0.695509
2        0.334545  0.000000  0.360544  0.196224  0.190292  0.695256
3        0.718627  0.000000  0.749364  0.089787  0.074036  0.695371
4        0.000000  0.000000  0.857243  0.694986  0.046826  0.695824
5        0.722932  0.000000  0.826485  0.074744  0.046025  0.695255
6        0.282248  0.000000  0.461061  0.210380  0.157303  0.695806
7        0.821170  0.000000  0.883657  0.047258  0.032057  0.695314
8        0.315788  0.224998  0.361249  0.202674  0.188665  0.242730
9        0.316618  0.200540  0.410223  0.203472  0.172814  0.261952
10       0.671880  0.520565  0.757040  0.090389  0.068758  0.138756
11       0.407282  0.249238  0.493969  0.173644  0.142808  0.232658
12       0.849984  0.783972  0.907862  0.041392  0.026198  0.056387
13       0.338326  0.305506  0.466662  0.195805  0.148930  0.206350
14       0.341016  0.244575  0.459493  0.197170  0.155943  0.237263
15       0.156007  0.000000  0.158804  0.223694  0.222555  0.645704
16       0.254880  0.000000  0.267297  0.187736  0.184252  0.645438
17       0.704149  0.000000  0.723834  0.055636  0.047483  0.645625
18       0.000000  0.000000  0.997829  0.645452  0.001316  0.645732
19       0.000000  0.000000  0.998042  0.630014  0.000840  0.646288
20       0.941406  0.740870  0.962260  0.020397  0.013683  0.064734
21       0.726779  0.000000  0.855226  0.062372  0.043720  0.645427
22       0.959762  0.865291  0.966661  0.015126  0.011609  0.036289
23       0.419496  0.000000  0.924392  0.134663  0.030275  0.646249
24       0.533004  0.000000  0.934244  0.104549  0.029240  0.645811
25       0.974317  0.953041  0.984027  0.009054  0.005274  0.016599
26       0.945554  0.701590  0.971197  0.021982  0.014262  0.076396
27       0.977256  0.964924  0.985516  0.007340  0.004938  0.013392
28       0.861079  0.540145  0.975825  0.039346  0.012404  0.119449
29       0.890166  0.652707  0.984221  0.033116  0.008447  0.072336

   loss_foreground
            median       min       max
0         2.206744  2.199567  4.349462
1         2.002761  1.928894  4.371080
2         1.470117  1.424437  4.306051
3         0.633244  0.545642  4.350795
4         4.286885  0.327937  4.369768
5         0.560341  0.346028  4.385149
6         1.579658  1.183989  4.343172
7         0.352289  0.241017  4.329037
8         1.524671  1.420097  1.827314
9         1.530626  1.297083  1.971031
10        0.677394  0.512157  1.039077
11        1.304435  1.068699  1.740811
12        0.308073  0.195291  0.423795
13        1.471718  1.112670  1.550271
14        1.477624  1.163495  1.778782
15        1.548898  1.541063  3.501782
16        1.299809  1.275683  3.547302
17        0.384797  0.328026  3.553816
18        3.497888  0.008715  3.606140
19        3.403332  0.005717  3.595575
20        0.140121  0.094339  0.447880
21        0.430266  0.292122  3.545794
22        0.103561  0.080373  0.250708
23        0.932256  0.209235  3.443993
24        0.723061  0.202070  3.613806
25        0.062444  0.036223  0.114795
26        0.148061  0.098620  0.525329
27        0.051365  0.033635  0.092431
28        0.270467  0.085723  0.820301
29        0.228317  0.058124  0.499989

[30 rows x 22 columns]

In [6]:
pivoted_df = grouped_df.pivot_table(index=group_keys)#, columns='extension', values=metrics, aggfunc='mean')

/tmp/ipykernel_2480217/3692313265.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  pivoted_df = grouped_df.pivot_table(index=group_keys)#, columns='extension', values=metrics, aggfunc='mean')

In [7]:
pivoted_df

                                                                 acc  \
                                                                 max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.888624
                                   4          linear        0.903130
                                   8          linear        0.930922
                                   16         linear        0.977157
                                   32         linear        0.987082
                conv_recurrent2    16         fft           0.984425
                                              last          0.942890
                                              linear        0.989762
                                              max_time      0.928812
                                              mean_time     0.936211
                cornn_model2       16         fft           0.976943
                                              last          0.947356
                                              linear        0.991697
                                              max_time      0.944388
                                              mean_time     0.942101
new_tetronimoes baseline1_flexible 2          linear        0.893240
                                   4          linear        0.912862
                                   8          linear        0.974733
                                   16         linear        0.999781
                                   32         linear        0.999824
                conv_recurrent2    16         fft           0.995757
                                              last          0.986217
                                              linear        0.996327
                                              max_time      0.992072
                                              mean_time     0.992849
                cornn_model2       16         fft           0.998231
                                              last          0.996557
                                              linear        0.998410
                                              max_time      0.997126
                                              mean_time     0.998252

                                                                      \
                                                              median
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.887748
                                   4          linear        0.899076
                                   8          linear        0.928060
                                   16         linear        0.972720
                                   32         linear        0.867376
                conv_recurrent2    16         fft           0.974344
                                              last          0.917567
                                              linear        0.983895
                                              max_time      0.922649
                                              mean_time     0.922605
                cornn_model2       16         fft           0.968943
                                              last          0.935317
                                              linear        0.986542
                                              max_time      0.925939
                                              mean_time     0.926018
new_tetronimoes baseline1_flexible 2          linear        0.893084
                                   4          linear        0.911918
                                   8          linear        0.972206
                                   16         linear        0.855584
                                   32         linear        0.855584
                conv_recurrent2    16         fft           0.993431
                                              last          0.975093
                                              linear        0.995471
                                              max_time      0.936548
                                              mean_time     0.951930
                cornn_model2       16         fft           0.997038
                                              last          0.993886
                                              linear        0.997418
                                              max_time      0.986642
                                              mean_time     0.989074

                                                                      \
                                                                 min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.867376
                                   4          linear        0.867376
                                   8          linear        0.867376
                                   16         linear        0.867376
                                   32         linear        0.867376
                conv_recurrent2    16         fft           0.867376
                                              last          0.867376
                                              linear        0.867376
                                              max_time      0.908388
                                              mean_time     0.898621
                cornn_model2       16         fft           0.951163
                                              last          0.911316
                                              linear        0.980632
                                              max_time      0.918815
                                              mean_time     0.911441
new_tetronimoes baseline1_flexible 2          linear        0.855584
                                   4          linear        0.855584
                                   8          linear        0.855584
                                   16         linear        0.855584
                                   32         linear        0.855584
                conv_recurrent2    16         fft           0.975504
                                              last          0.855584
                                              linear        0.986845
                                              max_time      0.855584
                                              mean_time     0.855584
                cornn_model2       16         fft           0.994583
                                              last          0.970125
                                              linear        0.995895
                                              max_time      0.951164
                                              mean_time     0.966247

                                                           acc_foreground  \
                                                                      max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear             0.175360
                                   4          linear             0.282722
                                   8          linear             0.488726
                                   16         linear             0.833224
                                   32         linear             0.906093
                conv_recurrent2    16         fft                0.885526
                                              last               0.582316
                                              linear             0.925005
                                              max_time           0.474936
                                              mean_time          0.533804
                cornn_model2       16         fft                0.835254
                                              last               0.614334
                                              linear             0.939604
                                              max_time           0.588908
                                              mean_time          0.571493
new_tetronimoes baseline1_flexible 2          linear             0.264227
                                   4          linear             0.402098
                                   8          linear             0.830295
                                   16         linear             0.998711
                                   32         linear             0.998848
                conv_recurrent2    16         fft                0.978538
                                              last               0.917751
                                              linear             0.981354
                                              max_time           0.957148
                                              mean_time          0.960767
                cornn_model2       16         fft                0.990969
                                              last               0.982680
                                              linear             0.991914
                                              max_time           0.985604
                                              mean_time          0.991209

                                                                      \
                                                              median
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.167325
                                   4          linear        0.252035
                                   8          linear        0.465001
                                   16         linear        0.810607
                                   32         linear        0.000000
                conv_recurrent2    16         fft           0.812225
                                              last          0.398685
                                              linear        0.883177
                                              max_time      0.435984
                                              mean_time     0.430604
                cornn_model2       16         fft           0.775031
                                              last          0.524660
                                              linear        0.901748
                                              max_time      0.455255
                                              mean_time     0.456219
new_tetronimoes baseline1_flexible 2          linear        0.263412
                                   4          linear        0.394114
                                   8          linear        0.815611
                                   16         linear        0.000000
                                   32         linear        0.000000
                conv_recurrent2    16         fft           0.965574
                                              last          0.835806
                                              linear        0.977153
                                              max_time      0.568981
                                              mean_time     0.675580
                cornn_model2       16         fft           0.984935
                                              last          0.968162
                                              linear        0.986924
                                              max_time      0.920335
                                              mean_time     0.935900

                                                                      \
                                                                 min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.000000
                                   4          linear        0.000000
                                   8          linear        0.000000
                                   16         linear        0.000000
                                   32         linear        0.000000
                conv_recurrent2    16         fft           0.000000
                                              last          0.000000
                                              linear        0.000000
                                              max_time      0.320290
                                              mean_time     0.267267
                cornn_model2       16         fft           0.647814
                                              last          0.345154
                                              linear        0.858823
                                              max_time      0.411114
                                              mean_time     0.340264
new_tetronimoes baseline1_flexible 2          linear        0.000000
                                   4          linear        0.000000
                                   8          linear        0.000000
                                   16         linear        0.000000
                                   32         linear        0.000000
                conv_recurrent2    16         fft           0.843169
                                              last          0.000000
                                              linear        0.922943
                                              max_time      0.000000
                                              mean_time     0.000000
                cornn_model2       16         fft           0.971896
                                              last          0.814525
                                              linear        0.979386
                                              max_time      0.685429
                                              mean_time     0.776540

                                                                 iou  \
                                                                 max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.802627
                                   4          linear        0.826121
                                   8          linear        0.873249
                                   16         linear        0.956573
                                   32         linear        0.975419
                conv_recurrent2    16         fft           0.970291
                                              last          0.894683
                                              linear        0.980460
                                              max_time      0.870382
                                              mean_time     0.883080
                cornn_model2       16         fft           0.956369
                                              last          0.902663
                                              linear        0.984205
                                              max_time      0.897361
                                              mean_time     0.893486
new_tetronimoes baseline1_flexible 2          linear        0.811122
                                   4          linear        0.842710
                                   8          linear        0.951286
                                   16         linear        0.999570
                                   32         linear        0.999656
                conv_recurrent2    16         fft           0.991751
                                              last          0.973207
                                              linear        0.992833
                                              max_time      0.984631
                                              mean_time     0.986316
                cornn_model2       16         fft           0.996547
                                              last          0.993381
                                              linear        0.996899
                                              max_time      0.994488
                                              mean_time     0.996588

                                                                      \
                                                              median
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.801498
                                   4          linear        0.819686
                                   8          linear        0.868159
                                   16         linear        0.948316
                                   32         linear        0.768509
                conv_recurrent2    16         fft           0.951420
                                              last          0.850484
                                              linear        0.969301
                                              max_time      0.859537
                                              mean_time     0.859492
                cornn_model2       16         fft           0.941420
                                              last          0.881606
                                              linear        0.974344
                                              max_time      0.865104
                                              mean_time     0.865325
new_tetronimoes baseline1_flexible 2          linear        0.810884
                                   4          linear        0.841182
                                   8          linear        0.946660
                                   16         linear        0.753765
                                   32         linear        0.753765
                conv_recurrent2    16         fft           0.987352
                                              last          0.951967
                                              linear        0.991205
                                              max_time      0.882922
                                              mean_time     0.909814
                cornn_model2       16         fft           0.994278
                                              last          0.988220
                                              linear        0.994984
                                              max_time      0.974147
                                              mean_time     0.978946

                                                                      \
                                                                 min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.768509
                                   4          linear        0.768509
                                   8          linear        0.768509
                                   16         linear        0.768509
                                   32         linear        0.768509
                conv_recurrent2    16         fft           0.768509
                                              last          0.768509
                                              linear        0.768509
                                              max_time      0.835328
                                              mean_time     0.819776
                cornn_model2       16         fft           0.909029
                                              last          0.840269
                                              linear        0.963070
                                              max_time      0.853580
                                              mean_time     0.840629
new_tetronimoes baseline1_flexible 2          linear        0.753765
                                   4          linear        0.753765
                                   8          linear        0.753765
                                   16         linear        0.753765
                                   32         linear        0.753765
                conv_recurrent2    16         fft           0.952892

In [8]:
pivoted_df = pivoted_df.round(2)

In [9]:
pivoted_df

                                                             acc               \
                                                             max median   min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.89   0.89  0.87
                                   4          linear        0.90   0.90  0.87
                                   8          linear        0.93   0.93  0.87
                                   16         linear        0.98   0.97  0.87
                                   32         linear        0.99   0.87  0.87
                conv_recurrent2    16         fft           0.98   0.97  0.87
                                              last          0.94   0.92  0.87
                                              linear        0.99   0.98  0.87
                                              max_time      0.93   0.92  0.91
                                              mean_time     0.94   0.92  0.90
                cornn_model2       16         fft           0.98   0.97  0.95
                                              last          0.95   0.94  0.91
                                              linear        0.99   0.99  0.98
                                              max_time      0.94   0.93  0.92
                                              mean_time     0.94   0.93  0.91
new_tetronimoes baseline1_flexible 2          linear        0.89   0.89  0.86
                                   4          linear        0.91   0.91  0.86
                                   8          linear        0.97   0.97  0.86
                                   16         linear        1.00   0.86  0.86
                                   32         linear        1.00   0.86  0.86
                conv_recurrent2    16         fft           1.00   0.99  0.98
                                              last          0.99   0.98  0.86
                                              linear        1.00   1.00  0.99
                                              max_time      0.99   0.94  0.86
                                              mean_time     0.99   0.95  0.86
                cornn_model2       16         fft           1.00   1.00  0.99
                                              last          1.00   0.99  0.97
                                              linear        1.00   1.00  1.00
                                              max_time      1.00   0.99  0.95
                                              mean_time     1.00   0.99  0.97

                                                           acc_foreground  \
                                                                      max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear                 0.18
                                   4          linear                 0.28
                                   8          linear                 0.49
                                   16         linear                 0.83
                                   32         linear                 0.91
                conv_recurrent2    16         fft                    0.89
                                              last                   0.58
                                              linear                 0.93
                                              max_time               0.47
                                              mean_time              0.53
                cornn_model2       16         fft                    0.84
                                              last                   0.61
                                              linear                 0.94
                                              max_time               0.59
                                              mean_time              0.57
new_tetronimoes baseline1_flexible 2          linear                 0.26
                                   4          linear                 0.40
                                   8          linear                 0.83
                                   16         linear                 1.00
                                   32         linear                 1.00
                conv_recurrent2    16         fft                    0.98
                                              last                   0.92
                                              linear                 0.98
                                              max_time               0.96
                                              mean_time              0.96
                cornn_model2       16         fft                    0.99
                                              last                   0.98
                                              linear                 0.99
                                              max_time               0.99
                                              mean_time              0.99

                                                                          iou  \
                                                           median   min   max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear         0.17  0.00  0.80
                                   4          linear         0.25  0.00  0.83
                                   8          linear         0.47  0.00  0.87
                                   16         linear         0.81  0.00  0.96
                                   32         linear         0.00  0.00  0.98
                conv_recurrent2    16         fft            0.81  0.00  0.97
                                              last           0.40  0.00  0.89
                                              linear         0.88  0.00  0.98
                                              max_time       0.44  0.32  0.87
                                              mean_time      0.43  0.27  0.88
                cornn_model2       16         fft            0.78  0.65  0.96
                                              last           0.52  0.35  0.90
                                              linear         0.90  0.86  0.98
                                              max_time       0.46  0.41  0.90
                                              mean_time      0.46  0.34  0.89
new_tetronimoes baseline1_flexible 2          linear         0.26  0.00  0.81
                                   4          linear         0.39  0.00  0.84
                                   8          linear         0.82  0.00  0.95
                                   16         linear         0.00  0.00  1.00
                                   32         linear         0.00  0.00  1.00
                conv_recurrent2    16         fft            0.97  0.84  0.99
                                              last           0.84  0.00  0.97
                                              linear         0.98  0.92  0.99
                                              max_time       0.57  0.00  0.98
                                              mean_time      0.68  0.00  0.99
                cornn_model2       16         fft            0.98  0.97  1.00
                                              last           0.97  0.81  0.99
                                              linear         0.99  0.98  1.00
                                              max_time       0.92  0.69  0.99
                                              mean_time      0.94  0.78  1.00

                                                                         \
                                                           median   min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear         0.80  0.77
                                   4          linear         0.82  0.77
                                   8          linear         0.87  0.77
                                   16         linear         0.95  0.77
                                   32         linear         0.77  0.77
                conv_recurrent2    16         fft            0.95  0.77
                                              last           0.85  0.77
                                              linear         0.97  0.77
                                              max_time       0.86  0.84
                                              mean_time      0.86  0.82
                cornn_model2       16         fft            0.94  0.91
                                              last           0.88  0.84
                                              linear         0.97  0.96
                                              max_time       0.87  0.85
                                              mean_time      0.87  0.84
new_tetronimoes baseline1_flexible 2          linear         0.81  0.75
                                   4          linear         0.84  0.75
                                   8          linear         0.95  0.75
                                   16         linear         0.75  0.75
                                   32         linear         0.75  0.75
                conv_recurrent2    16         fft            0.99  0.95
                                              last           0.95  0.75
                                              linear         0.99  0.97
                                              max_time       0.88  0.75
                                              mean_time      0.91  0.75
                cornn_model2       16         fft            0.99  0.99
                                              last           0.99  0.94
                                              linear         0.99  0.99
                                              max_time       0.97  0.91
                                              mean_time      0.98  0.94

                                                           iou_foreground  \
                                                                      max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear                 0.12
                                   4          linear                 0.18
                                   8          linear                 0.36
                                   16         linear                 0.75
                                   32         linear                 0.86
                conv_recurrent2    16         fft                    0.83
                                              last                   0.46
                                              linear                 0.88
                                              max_time               0.36
                                              mean_time              0.41
                cornn_model2       16         fft                    0.76
                                              last                   0.49
                                              linear                 0.91
                                              max_time               0.47
                                              mean_time              0.46
new_tetronimoes baseline1_flexible 2          linear                 0.16
                                   4          linear                 0.27
                                   8          linear                 0.72
                                   16         linear                 1.00
                                   32         linear                 1.00
                conv_recurrent2    16         fft                    0.96
                                              last                   0.86
                                              linear                 0.97
                                              max_time               0.92
                                              mean_time              0.93
                cornn_model2       16         fft                    0.98
                                              last                   0.97
                                              linear                 0.99
                                              max_time               0.98
                                              mean_time              0.98

                                                                         loss  \
                                                           median   min   max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear         0.10  0.00  0.70
                                   4          linear         0.17  0.00  0.70
                                   8          linear         0.33  0.00  0.70
                                   16         linear         0.72  0.00  0.70
                                   32         linear         0.00  0.00  0.70
                conv_recurrent2    16         fft            0.72  0.00  0.70
                                              last           0.28  0.00  0.70
                                              linear         0.82  0.00  0.70
                                              max_time       0.32  0.22  0.24
                                              mean_time      0.32  0.20  0.26
                cornn_model2       16         fft            0.67  0.52  0.14
                                              last           0.41  0.25  0.23
                                              linear         0.85  0.78  0.06
                                              max_time       0.34  0.31  0.21
                                              mean_time      0.34  0.24  0.24
new_tetronimoes baseline1_flexible 2          linear         0.16  0.00  0.65
                                   4          linear         0.25  0.00  0.65
                                   8          linear         0.70  0.00  0.65
                                   16         linear         0.00  0.00  0.65
                                   32         linear         0.00  0.00  0.65
                conv_recurrent2    16         fft            0.94  0.74  0.06
                                              last           0.73  0.00  0.65
                                              linear         0.96  0.87  0.04
                                              max_time       0.42  0.00  0.65
                                              mean_time      0.53  0.00  0.65
                cornn_model2       16         fft            0.97  0.95  0.02
                                              last           0.95  0.70  0.08
                                              linear         0.98  0.96  0.01
                                              max_time       0.86  0.54  0.12
                                              mean_time      0.89  0.65  0.07

                                                                         \
                                                           median   min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear         0.29  0.29
                                   4          linear         0.27  0.26
                                   8          linear         0.20  0.19
                                   16         linear         0.09  0.07
                                   32         linear         0.69  0.05
                conv_recurrent2    16         fft            0.07  0.05
                                              last           0.21  0.16
                                              linear         0.05  0.03
                                              max_time       0.20  0.19
                                              mean_time      0.20  0.17
                cornn_model2       16         fft            0.09  0.07
                                              last           0.17  0.14
                                              linear         0.04  0.03
                                              max_time       0.20  0.15
                                              mean_time      0.20  0.16
new_tetronimoes baseline1_flexible 2          linear         0.22  0.22
                                   4          linear         0.19  0.18
                                   8          linear         0.06  0.05
                                   16         linear         0.65  0.00
                                   32         linear         0.63  0.00
                conv_recurrent2    16         fft            0.02  0.01
                                              last           0.06  0.04
                                              linear         0.02  0.01
                                              max_time       0.13  0.03
                                              mean_time      0.10  0.03
                cornn_model2       16         fft            0.01  0.01
                                              last           0.02  0.01
                                              linear         0.01  0.00
                                              max_time       0.04  0.01
                                              mean_time      0.03  0.01

                                                           loss_foreground  \
                                                                       max
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear                  4.35
                                   4          linear                  4.37
                                   8          linear                  4.31
                                   16         linear                  4.35
                                   32         linear                  4.37
                conv_recurrent2    16         fft                     4.39
                                              last                    4.34
                                              linear                  4.33
                                              max_time                1.83
                                              mean_time               1.97
                cornn_model2       16         fft                     1.04
                                              last                    1.74
                                              linear                  0.42
                                              max_time                1.55
                                              mean_time               1.78
new_tetronimoes baseline1_flexible 2          linear                  3.50
                                   4          linear                  3.55
                                   8          linear                  3.55
                                   16         linear                  3.61
                                   32         linear                  3.60
                conv_recurrent2    16         fft                     0.45
                                              last                    3.55
                                              linear                  0.25
                                              max_time                3.44
                                              mean_time               3.61
                cornn_model2       16         fft                     0.11
                                              last                    0.53
                                              linear                  0.09
                                              max_time                0.82
                                              mean_time               0.50


                                                           median   min
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear         2.21  2.20

In [10]:
datasets = ["mnist", "new_tetronimoes"]
models = ["cornn_model2", "conv_recurrent2", "baseline1_flexible"]
num_layers = [2, 4, 8, 16, 32]
readouts = ["linear", "fft", "last", "mean_time", "max_time"]

In [11]:
results = {}
for dataset in datasets:
    if dataset not in results:
        results[dataset] = {}
    for model in models:
        if model not in results[dataset]:
            results[dataset][model] = {}
        if model == "baseline1_flexible":
            for layer in num_layers:
                df1 = pivoted_df.loc[(dataset, model, layer, "linear")]
                results[dataset][model][layer] = df1
        else:
            for readout in readouts:
                df1 = pivoted_df.loc[(dataset, model, 16, readout)]
                results[dataset][model][readout] = df1

In [12]:
def do_concats(dataset, models):
    df1 = pd.concat(results[dataset][models[2]], axis=1).T
    df2 = pd.concat(results[dataset][models[1]], axis=1).T
    df3 = pd.concat(results[dataset][models[0]], axis=1).T
    return pd.concat((df1, df2, df3), axis=0, keys=("CNN", "LSTM", "CoRNN"))

In [13]:
df1 = do_concats("mnist", models)
df2 = do_concats("new_tetronimoes", models)

In [14]:
df1 = pd.concat((df1, df2), axis=0, keys=("MNIST", "Tetrominoes"))

In [15]:
df1

                              acc              acc_foreground               \
                              max median   min            max median   min
MNIST       CNN   2          0.89   0.89  0.87           0.18   0.17  0.00
                  4          0.90   0.90  0.87           0.28   0.25  0.00
                  8          0.93   0.93  0.87           0.49   0.47  0.00
                  16         0.98   0.97  0.87           0.83   0.81  0.00
                  32         0.99   0.87  0.87           0.91   0.00  0.00
            LSTM  linear     0.99   0.98  0.87           0.93   0.88  0.00
                  fft        0.98   0.97  0.87           0.89   0.81  0.00
                  last       0.94   0.92  0.87           0.58   0.40  0.00
                  mean_time  0.94   0.92  0.90           0.53   0.43  0.27
                  max_time   0.93   0.92  0.91           0.47   0.44  0.32
            CoRNN linear     0.99   0.99  0.98           0.94   0.90  0.86
                  fft        0.98   0.97  0.95           0.84   0.78  0.65
                  last       0.95   0.94  0.91           0.61   0.52  0.35
                  mean_time  0.94   0.93  0.91           0.57   0.46  0.34
                  max_time   0.94   0.93  0.92           0.59   0.46  0.41
Tetrominoes CNN   2          0.89   0.89  0.86           0.26   0.26  0.00
                  4          0.91   0.91  0.86           0.40   0.39  0.00
                  8          0.97   0.97  0.86           0.83   0.82  0.00
                  16         1.00   0.86  0.86           1.00   0.00  0.00
                  32         1.00   0.86  0.86           1.00   0.00  0.00
            LSTM  linear     1.00   1.00  0.99           0.98   0.98  0.92
                  fft        1.00   0.99  0.98           0.98   0.97  0.84
                  last       0.99   0.98  0.86           0.92   0.84  0.00
                  mean_time  0.99   0.95  0.86           0.96   0.68  0.00
                  max_time   0.99   0.94  0.86           0.96   0.57  0.00
            CoRNN linear     1.00   1.00  1.00           0.99   0.99  0.98
                  fft        1.00   1.00  0.99           0.99   0.98  0.97
                  last       1.00   0.99  0.97           0.98   0.97  0.81
                  mean_time  1.00   0.99  0.97           0.99   0.94  0.78
                  max_time   1.00   0.99  0.95           0.99   0.92  0.69

                              iou              iou_foreground               \
                              max median   min            max median   min
MNIST       CNN   2          0.80   0.80  0.77           0.12   0.10  0.00
                  4          0.83   0.82  0.77           0.18   0.17  0.00
                  8          0.87   0.87  0.77           0.36   0.33  0.00
                  16         0.96   0.95  0.77           0.75   0.72  0.00
                  32         0.98   0.77  0.77           0.86   0.00  0.00
            LSTM  linear     0.98   0.97  0.77           0.88   0.82  0.00
                  fft        0.97   0.95  0.77           0.83   0.72  0.00
                  last       0.89   0.85  0.77           0.46   0.28  0.00
                  mean_time  0.88   0.86  0.82           0.41   0.32  0.20
                  max_time   0.87   0.86  0.84           0.36   0.32  0.22
            CoRNN linear     0.98   0.97  0.96           0.91   0.85  0.78
                  fft        0.96   0.94  0.91           0.76   0.67  0.52
                  last       0.90   0.88  0.84           0.49   0.41  0.25
                  mean_time  0.89   0.87  0.84           0.46   0.34  0.24
                  max_time   0.90   0.87  0.85           0.47   0.34  0.31
Tetrominoes CNN   2          0.81   0.81  0.75           0.16   0.16  0.00
                  4          0.84   0.84  0.75           0.27   0.25  0.00
                  8          0.95   0.95  0.75           0.72   0.70  0.00
                  16         1.00   0.75  0.75           1.00   0.00  0.00
                  32         1.00   0.75  0.75           1.00   0.00  0.00
            LSTM  linear     0.99   0.99  0.97           0.97   0.96  0.87
                  fft        0.99   0.99  0.95           0.96   0.94  0.74
                  last       0.97   0.95  0.75           0.86   0.73  0.00
                  mean_time  0.99   0.91  0.75           0.93   0.53  0.00
                  max_time   0.98   0.88  0.75           0.92   0.42  0.00
            CoRNN linear     1.00   0.99  0.99           0.99   0.98  0.96
                  fft        1.00   0.99  0.99           0.98   0.97  0.95
                  last       0.99   0.99  0.94           0.97   0.95  0.70
                  mean_time  1.00   0.98  0.94           0.98   0.89  0.65
                  max_time   0.99   0.97  0.91           0.98   0.86  0.54

                             loss              loss_foreground
                              max median   min             max median   min
MNIST       CNN   2          0.70   0.29  0.29            4.35   2.21  2.20
                  4          0.70   0.27  0.26            4.37   2.00  1.93
                  8          0.70   0.20  0.19            4.31   1.47  1.42
                  16         0.70   0.09  0.07            4.35   0.63  0.55
                  32         0.70   0.69  0.05            4.37   4.29  0.33
            LSTM  linear     0.70   0.05  0.03            4.33   0.35  0.24
                  fft        0.70   0.07  0.05            4.39   0.56  0.35
                  last       0.70   0.21  0.16            4.34   1.58  1.18
                  mean_time  0.26   0.20  0.17            1.97   1.53  1.30
                  max_time   0.24   0.20  0.19            1.83   1.52  1.42
            CoRNN linear     0.06   0.04  0.03            0.42   0.31  0.20
                  fft        0.14   0.09  0.07            1.04   0.68  0.51
                  last       0.23   0.17  0.14            1.74   1.30  1.07
                  mean_time  0.24   0.20  0.16            1.78   1.48  1.16
                  max_time   0.21   0.20  0.15            1.55   1.47  1.11
Tetrominoes CNN   2          0.65   0.22  0.22            3.50   1.55  1.54
                  4          0.65   0.19  0.18            3.55   1.30  1.28
                  8          0.65   0.06  0.05            3.55   0.38  0.33
                  16         0.65   0.65  0.00            3.61   3.50  0.01
                  32         0.65   0.63  0.00            3.60   3.40  0.01
            LSTM  linear     0.04   0.02  0.01            0.25   0.10  0.08
                  fft        0.06   0.02  0.01            0.45   0.14  0.09
                  last       0.65   0.06  0.04            3.55   0.43  0.29
                  mean_time  0.65   0.10  0.03            3.61   0.72  0.20
                  max_time   0.65   0.13  0.03            3.44   0.93  0.21
            CoRNN linear     0.01   0.01  0.00            0.09   0.05  0.03
                  fft        0.02   0.01  0.01            0.11   0.06  0.04
                  last       0.08   0.02  0.01            0.53   0.15  0.10
                  mean_time  0.07   0.03  0.01            0.50   0.23  0.06
                  max_time   0.12   0.04  0.01            0.82   0.27  0.09

In [16]:
df1.to_csv("results_scores/scores_processed_min_max.csv", index=True)
df1.to_latex("results_scores/scores_processed_min_max", index=True, float_format="%.2f")