In [45]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
# Specify the path to your CSV file
csv_file = 'results_scores/scores_test_mnist_tetro.csv'
df = pd.read_csv(csv_file)
df = df.drop(["run_name", "max_iters"], axis=1)

In [47]:
df.head()

,dataset,model_type,readout_type,num_layers,extension,loss,iou,acc,loss_foreground,iou_foreground,acc_foreground
0,mnist,cornn_model2,mean_time,16,1,0.155943,0.893486,0.942101,1.163495,0.459493,0.571493
1,mnist,cornn_model2,max_time,16,1,0.203852,0.854802,0.919819,1.532727,0.306960,0.416585
2,mnist,cornn_model2,fft,16,1,0.084844,0.944797,0.970739,0.634949,0.696490,0.790904
3,mnist,cornn_model2,last,16,1,0.190265,0.865763,0.926200,1.431079,0.342051,0.456508
4,mnist,cornn_model2,linear,16,1,0.026198,0.984205,0.991697,0.195291,0.907862,0.939604

In [48]:
# Define the grouping keys
group_keys = ["dataset", "model_type", "num_layers", "readout_type"]

# Define the metrics for which statistics should be computed
metrics = ["acc", "acc_foreground", "iou", "iou_foreground", "loss", "loss_foreground"]

# Group by the specified keys and compute statistics across the "extension" category
grouped_df = df.groupby(group_keys).agg({
    metric: ['mean', 'std'] for metric in metrics
}).reset_index()

In [49]:
grouped_df

            dataset          model_type num_layers readout_type       acc  \
                                                                     mean
0             mnist  baseline1_flexible          2       linear  0.885204
1             mnist  baseline1_flexible          4       linear  0.891928
2             mnist  baseline1_flexible          8       linear  0.921972
3             mnist  baseline1_flexible         16       linear  0.941925
4             mnist  baseline1_flexible         32       linear  0.902787
5             mnist     conv_recurrent2         16          fft  0.963964
6             mnist     conv_recurrent2         16         last  0.907413
7             mnist     conv_recurrent2         16       linear  0.971187
8             mnist     conv_recurrent2         16     max_time  0.921344
9             mnist     conv_recurrent2         16    mean_time  0.920584
10            mnist        cornn_model2         16          fft  0.966558
11            mnist        cornn_model2         16         last  0.932464
12            mnist        cornn_model2         16       linear  0.986683
13            mnist        cornn_model2         16     max_time  0.929094
14            mnist        cornn_model2         16    mean_time  0.926620
15  new_tetronimoes  baseline1_flexible          2       linear  0.889327
16  new_tetronimoes  baseline1_flexible          4       linear  0.899656
17  new_tetronimoes  baseline1_flexible          8       linear  0.960891
18  new_tetronimoes  baseline1_flexible         16       linear  0.913046
19  new_tetronimoes  baseline1_flexible         32       linear  0.902424
20  new_tetronimoes     conv_recurrent2         16          fft  0.991393
21  new_tetronimoes     conv_recurrent2         16         last  0.939126
22  new_tetronimoes     conv_recurrent2         16       linear  0.994047
23  new_tetronimoes     conv_recurrent2         16     max_time  0.944433
24  new_tetronimoes     conv_recurrent2         16    mean_time  0.947433
25  new_tetronimoes        cornn_model2         16          fft  0.996657
26  new_tetronimoes        cornn_model2         16         last  0.989975
27  new_tetronimoes        cornn_model2         16       linear  0.997360
28  new_tetronimoes        cornn_model2         16     max_time  0.981104
29  new_tetronimoes        cornn_model2         16    mean_time  0.987110

             acc_foreground                 iou           iou_foreground  \
         std           mean       std      mean       std           mean
0   0.006467       0.137696  0.056815  0.797436  0.010361       0.096926
1   0.013943       0.191907  0.113703  0.808227  0.022403       0.130056
2   0.019268       0.420465  0.148326  0.858190  0.031664       0.303198
3   0.051547       0.568556  0.392968  0.895875  0.088101       0.504716
4   0.057025       0.269597  0.434122  0.829643  0.098452       0.254372
5   0.035072       0.733359  0.265593  0.933788  0.060361       0.655751
6   0.029195       0.315869  0.229380  0.834744  0.048533       0.237582
7   0.036928       0.786371  0.279576  0.947261  0.063741       0.727617
8   0.006556       0.422196  0.051231  0.857292  0.011259       0.308266
9   0.012298       0.420070  0.088628  0.856224  0.020815       0.310299
10  0.007465       0.758196  0.054940  0.937071  0.013703       0.653681
11  0.010133       0.502144  0.075817  0.876580  0.017583       0.385575
12  0.003318       0.903142  0.024036  0.974612  0.006324       0.851559
13  0.009893       0.481618  0.069946  0.870818  0.017138       0.365865
14  0.010509       0.459858  0.080415  0.866694  0.018110       0.351584
15  0.011857       0.237035  0.083288  0.805159  0.018059       0.141028
16  0.023433       0.309378  0.164534  0.822203  0.036410       0.202498
17  0.037023       0.736252  0.258801  0.928029  0.061275       0.637404
18  0.074184       0.398361  0.514287  0.851665  0.126392       0.397193
19  0.068066       0.325112  0.471377  0.832994  0.116152       0.315986
20  0.006221       0.950065  0.042029  0.983313  0.011954       0.913557
21  0.059146       0.585506  0.414374  0.892675  0.098849       0.517901
22  0.002965       0.967826  0.018422  0.988424  0.005747       0.943175
23  0.042458       0.623129  0.296966  0.899412  0.073013       0.521604
24  0.035544       0.644699  0.248809  0.903903  0.059461       0.530761
25  0.001277       0.983007  0.006503  0.993539  0.002429       0.970947
26  0.008986       0.941893  0.057795  0.980765  0.017190       0.903100
27  0.000801       0.986613  0.004001  0.994876  0.001536       0.976753
28  0.015703       0.882091  0.105268  0.964056  0.029434       0.813508
29  0.010231       0.920877  0.069100  0.975243  0.019581       0.868960

                  loss           loss_foreground
         std      mean       std            mean       std
0   0.035082  0.335372  0.126608        2.438303  0.672433
1   0.072713  0.353670  0.180490        2.487242  0.987029
2   0.107356  0.246205  0.157832        1.756597  0.896294
3   0.349516  0.268090  0.294902        1.733218  1.797337
4   0.409649  0.502604  0.310103        3.122953  1.909887
5   0.246175  0.135571  0.198137        0.934375  1.226123
6   0.176584  0.347595  0.240702        2.341111  1.377953
7   0.262958  0.115465  0.204342        0.777173  1.253621
8   0.044389  0.208089  0.017711        1.565778  0.133851
9   0.073959  0.209241  0.028952        1.572524  0.218610
10  0.069234  0.096573  0.020127        0.722897  0.151166
11  0.071444  0.179326  0.025237        1.344789  0.189526
12  0.036540  0.040364  0.009169        0.301892  0.068959
13  0.066924  0.185617  0.022074        1.394019  0.167893
14  0.073517  0.196494  0.027447        1.472837  0.207040
15  0.049574  0.265871  0.133461        1.744002  0.617636
16  0.107664  0.280332  0.192462        1.756685  0.944311
17  0.224217  0.114164  0.186803        0.698366  1.003895
18  0.512790  0.388572  0.331743        2.141911  1.825474
19  0.473194  0.407550  0.307959        2.262693  1.667235
20  0.069292  0.025777  0.015269        0.177558  0.105906
21  0.376510  0.238477  0.281948        1.371718  1.509695
22  0.032128  0.018683  0.007568        0.128714  0.052332
23  0.309664  0.157857  0.180662        0.989714  0.946965
24  0.231322  0.149086  0.176724        0.945811  0.956953
25  0.010496  0.010095  0.003926        0.069499  0.027119
26  0.094380  0.030604  0.020881        0.209248  0.142573
27  0.006741  0.007861  0.002428        0.054213  0.016862
28  0.154575  0.050200  0.034680        0.345576  0.238896
29  0.110309  0.035169  0.020869        0.242469  0.143584

In [50]:
#grouped_df.to_csv("results/scores_processed1.csv", index=True)

In [51]:
pivoted_df = grouped_df.pivot_table(index=group_keys)#, columns='extension', values=metrics, aggfunc='mean')

/tmp/ipykernel_729463/3692313265.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  pivoted_df = grouped_df.pivot_table(index=group_keys)#, columns='extension', values=metrics, aggfunc='mean')

In [52]:
pivoted_df

                                                                 acc  \
                                                                mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.885204
                                   4          linear        0.891928
                                   8          linear        0.921972
                                   16         linear        0.941925
                                   32         linear        0.902787
                conv_recurrent2    16         fft           0.963964
                                              last          0.907413
                                              linear        0.971187
                                              max_time      0.921344
                                              mean_time     0.920584
                cornn_model2       16         fft           0.966558
                                              last          0.932464
                                              linear        0.986683
                                              max_time      0.929094
                                              mean_time     0.926620
new_tetronimoes baseline1_flexible 2          linear        0.889327
                                   4          linear        0.899656
                                   8          linear        0.960891
                                   16         linear        0.913046
                                   32         linear        0.902424
                conv_recurrent2    16         fft           0.991393
                                              last          0.939126
                                              linear        0.994047
                                              max_time      0.944433
                                              mean_time     0.947433
                cornn_model2       16         fft           0.996657
                                              last          0.989975
                                              linear        0.997360
                                              max_time      0.981104
                                              mean_time     0.987110

                                                                      \
                                                                 std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.006467
                                   4          linear        0.013943
                                   8          linear        0.019268
                                   16         linear        0.051547
                                   32         linear        0.057025
                conv_recurrent2    16         fft           0.035072
                                              last          0.029195
                                              linear        0.036928
                                              max_time      0.006556
                                              mean_time     0.012298
                cornn_model2       16         fft           0.007465
                                              last          0.010133
                                              linear        0.003318
                                              max_time      0.009893
                                              mean_time     0.010509
new_tetronimoes baseline1_flexible 2          linear        0.011857
                                   4          linear        0.023433
                                   8          linear        0.037023
                                   16         linear        0.074184
                                   32         linear        0.068066
                conv_recurrent2    16         fft           0.006221
                                              last          0.059146
                                              linear        0.002965
                                              max_time      0.042458
                                              mean_time     0.035544
                cornn_model2       16         fft           0.001277
                                              last          0.008986
                                              linear        0.000801
                                              max_time      0.015703
                                              mean_time     0.010231

                                                           acc_foreground  \
                                                                     mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear             0.137696
                                   4          linear             0.191907
                                   8          linear             0.420465
                                   16         linear             0.568556
                                   32         linear             0.269597
                conv_recurrent2    16         fft                0.733359
                                              last               0.315869
                                              linear             0.786371
                                              max_time           0.422196
                                              mean_time          0.420070
                cornn_model2       16         fft                0.758196
                                              last               0.502144
                                              linear             0.903142
                                              max_time           0.481618
                                              mean_time          0.459858
new_tetronimoes baseline1_flexible 2          linear             0.237035
                                   4          linear             0.309378
                                   8          linear             0.736252
                                   16         linear             0.398361
                                   32         linear             0.325112
                conv_recurrent2    16         fft                0.950065
                                              last               0.585506
                                              linear             0.967826
                                              max_time           0.623129
                                              mean_time          0.644699
                cornn_model2       16         fft                0.983007
                                              last               0.941893
                                              linear             0.986613
                                              max_time           0.882091
                                              mean_time          0.920877

                                                                      \
                                                                 std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.056815
                                   4          linear        0.113703
                                   8          linear        0.148326
                                   16         linear        0.392968
                                   32         linear        0.434122
                conv_recurrent2    16         fft           0.265593
                                              last          0.229380
                                              linear        0.279576
                                              max_time      0.051231
                                              mean_time     0.088628
                cornn_model2       16         fft           0.054940
                                              last          0.075817
                                              linear        0.024036
                                              max_time      0.069946
                                              mean_time     0.080415
new_tetronimoes baseline1_flexible 2          linear        0.083288
                                   4          linear        0.164534
                                   8          linear        0.258801
                                   16         linear        0.514287
                                   32         linear        0.471377
                conv_recurrent2    16         fft           0.042029
                                              last          0.414374
                                              linear        0.018422
                                              max_time      0.296966
                                              mean_time     0.248809
                cornn_model2       16         fft           0.006503
                                              last          0.057795
                                              linear        0.004001
                                              max_time      0.105268
                                              mean_time     0.069100

                                                                 iou  \
                                                                mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.797436
                                   4          linear        0.808227
                                   8          linear        0.858190
                                   16         linear        0.895875
                                   32         linear        0.829643
                conv_recurrent2    16         fft           0.933788
                                              last          0.834744
                                              linear        0.947261
                                              max_time      0.857292
                                              mean_time     0.856224
                cornn_model2       16         fft           0.937071
                                              last          0.876580
                                              linear        0.974612
                                              max_time      0.870818
                                              mean_time     0.866694
new_tetronimoes baseline1_flexible 2          linear        0.805159
                                   4          linear        0.822203
                                   8          linear        0.928029
                                   16         linear        0.851665
                                   32         linear        0.832994
                conv_recurrent2    16         fft           0.983313
                                              last          0.892675
                                              linear        0.988424
                                              max_time      0.899412
                                              mean_time     0.903903
                cornn_model2       16         fft           0.993539
                                              last          0.980765
                                              linear        0.994876
                                              max_time      0.964056
                                              mean_time     0.975243

                                                                      \
                                                                 std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.010361
                                   4          linear        0.022403
                                   8          linear        0.031664
                                   16         linear        0.088101
                                   32         linear        0.098452
                conv_recurrent2    16         fft           0.060361
                                              last          0.048533
                                              linear        0.063741
                                              max_time      0.011259
                                              mean_time     0.020815
                cornn_model2       16         fft           0.013703
                                              last          0.017583
                                              linear        0.006324
                                              max_time      0.017138
                                              mean_time     0.018110
new_tetronimoes baseline1_flexible 2          linear        0.018059
                                   4          linear        0.036410
                                   8          linear        0.061275
                                   16         linear        0.126392
                                   32         linear        0.116152
                conv_recurrent2    16         fft           0.011954
                                              last          0.098849
                                              linear        0.005747
                                              max_time      0.073013
                                              mean_time     0.059461
                cornn_model2       16         fft           0.002429
                                              last          0.017190
                                              linear        0.001536
                                              max_time      0.029434
                                              mean_time     0.019581

                                                           iou_foreground  \
                                                                     mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear             0.096926
                                   4          linear             0.130056
                                   8          linear             0.303198
                                   16         linear             0.504716
                                   32         linear             0.254372
                conv_recurrent2    16         fft                0.655751
                                              last               0.237582
                                              linear             0.727617
                                              max_time           0.308266
                                              mean_time          0.310299
                cornn_model2       16         fft                0.653681
                                              last               0.385575
                                              linear             0.851559
                                              max_time           0.365865
                                              mean_time          0.351584
new_tetronimoes baseline1_flexible 2          linear             0.141028
                                   4          linear             0.202498
                                   8          linear             0.637404
                                   16         linear             0.397193
                                   32         linear             0.315986
                conv_recurrent2    16         fft                0.913557
                                              last               0.517901
                                              linear             0.943175
                                              max_time           0.521604
                                              mean_time          0.530761
                cornn_model2       16         fft                0.970947
                                              last               0.903100
                                              linear             0.976753
                                              max_time           0.813508
                                              mean_time          0.868960

                                                                      \
                                                                 std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.035082
                                   4          linear        0.072713
                                   8          linear        0.107356
                                   16         linear        0.349516
                                   32         linear        0.409649
                conv_recurrent2    16         fft           0.246175
                                              last          0.176584
                                              linear        0.262958
                                              max_time      0.044389
                                              mean_time     0.073959
                cornn_model2       16         fft           0.069234
                                              last          0.071444
                                              linear        0.036540
                                              max_time      0.066924
                                              mean_time     0.073517
new_tetronimoes baseline1_flexible 2          linear        0.049574
                                   4          linear        0.107664
                                   8          linear        0.224217
                                   16         linear        0.512790
                                   32         linear        0.473194
                conv_recurrent2    16         fft           0.069292
                                              last          0.376510
                                              linear        0.032128
                                              max_time      0.309664
                                              mean_time     0.231322
                cornn_model2       16         fft           0.010496
                                              last          0.094380
                                              linear        0.006741
                                              max_time      0.154575
                                              mean_time     0.110309

                                                                loss  \
                                                                mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.335372
                                   4          linear        0.353670
                                   8          linear        0.246205
                                   16         linear        0.268090
                                   32         linear        0.502604
                conv_recurrent2    16         fft           0.135571
                                              last          0.347595
                                              linear        0.115465
                                              max_time      0.208089
                                              mean_time     0.209241
                cornn_model2       16         fft           0.096573
                                              last          0.179326
                                              linear        0.040364
                                              max_time      0.185617
                                              mean_time     0.196494
new_tetronimoes baseline1_flexible 2          linear        0.265871
                                   4          linear        0.280332
                                   8          linear        0.114164
                                   16         linear        0.388572

In [53]:
pivoted_df = pivoted_df.round(2)

In [54]:
pivoted_df

                                                             acc        \
                                                            mean   std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.89  0.01
                                   4          linear        0.89  0.01
                                   8          linear        0.92  0.02
                                   16         linear        0.94  0.05
                                   32         linear        0.90  0.06
                conv_recurrent2    16         fft           0.96  0.04
                                              last          0.91  0.03
                                              linear        0.97  0.04
                                              max_time      0.92  0.01
                                              mean_time     0.92  0.01
                cornn_model2       16         fft           0.97  0.01
                                              last          0.93  0.01
                                              linear        0.99  0.00
                                              max_time      0.93  0.01
                                              mean_time     0.93  0.01
new_tetronimoes baseline1_flexible 2          linear        0.89  0.01
                                   4          linear        0.90  0.02
                                   8          linear        0.96  0.04
                                   16         linear        0.91  0.07
                                   32         linear        0.90  0.07
                conv_recurrent2    16         fft           0.99  0.01
                                              last          0.94  0.06
                                              linear        0.99  0.00
                                              max_time      0.94  0.04
                                              mean_time     0.95  0.04
                cornn_model2       16         fft           1.00  0.00
                                              last          0.99  0.01
                                              linear        1.00  0.00
                                              max_time      0.98  0.02
                                              mean_time     0.99  0.01

                                                           acc_foreground  \
                                                                     mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear                 0.14
                                   4          linear                 0.19
                                   8          linear                 0.42
                                   16         linear                 0.57
                                   32         linear                 0.27
                conv_recurrent2    16         fft                    0.73
                                              last                   0.32
                                              linear                 0.79
                                              max_time               0.42
                                              mean_time              0.42
                cornn_model2       16         fft                    0.76
                                              last                   0.50
                                              linear                 0.90
                                              max_time               0.48
                                              mean_time              0.46
new_tetronimoes baseline1_flexible 2          linear                 0.24
                                   4          linear                 0.31
                                   8          linear                 0.74
                                   16         linear                 0.40
                                   32         linear                 0.33
                conv_recurrent2    16         fft                    0.95
                                              last                   0.59
                                              linear                 0.97
                                              max_time               0.62
                                              mean_time              0.64
                cornn_model2       16         fft                    0.98
                                              last                   0.94
                                              linear                 0.99
                                              max_time               0.88
                                              mean_time              0.92

                                                                   iou        \
                                                             std  mean   std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.06  0.80  0.01
                                   4          linear        0.11  0.81  0.02
                                   8          linear        0.15  0.86  0.03
                                   16         linear        0.39  0.90  0.09
                                   32         linear        0.43  0.83  0.10
                conv_recurrent2    16         fft           0.27  0.93  0.06
                                              last          0.23  0.83  0.05
                                              linear        0.28  0.95  0.06
                                              max_time      0.05  0.86  0.01
                                              mean_time     0.09  0.86  0.02
                cornn_model2       16         fft           0.05  0.94  0.01
                                              last          0.08  0.88  0.02
                                              linear        0.02  0.97  0.01
                                              max_time      0.07  0.87  0.02
                                              mean_time     0.08  0.87  0.02
new_tetronimoes baseline1_flexible 2          linear        0.08  0.81  0.02
                                   4          linear        0.16  0.82  0.04
                                   8          linear        0.26  0.93  0.06
                                   16         linear        0.51  0.85  0.13
                                   32         linear        0.47  0.83  0.12
                conv_recurrent2    16         fft           0.04  0.98  0.01
                                              last          0.41  0.89  0.10
                                              linear        0.02  0.99  0.01
                                              max_time      0.30  0.90  0.07
                                              mean_time     0.25  0.90  0.06
                cornn_model2       16         fft           0.01  0.99  0.00
                                              last          0.06  0.98  0.02
                                              linear        0.00  0.99  0.00
                                              max_time      0.11  0.96  0.03
                                              mean_time     0.07  0.98  0.02

                                                           iou_foreground  \
                                                                     mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear                 0.10
                                   4          linear                 0.13
                                   8          linear                 0.30
                                   16         linear                 0.50
                                   32         linear                 0.25
                conv_recurrent2    16         fft                    0.66
                                              last                   0.24
                                              linear                 0.73
                                              max_time               0.31
                                              mean_time              0.31
                cornn_model2       16         fft                    0.65
                                              last                   0.39
                                              linear                 0.85
                                              max_time               0.37
                                              mean_time              0.35
new_tetronimoes baseline1_flexible 2          linear                 0.14
                                   4          linear                 0.20
                                   8          linear                 0.64
                                   16         linear                 0.40
                                   32         linear                 0.32
                conv_recurrent2    16         fft                    0.91
                                              last                   0.52
                                              linear                 0.94
                                              max_time               0.52
                                              mean_time              0.53
                cornn_model2       16         fft                    0.97
                                              last                   0.90
                                              linear                 0.98
                                              max_time               0.81
                                              mean_time              0.87

                                                                  loss        \
                                                             std  mean   std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.04  0.34  0.13
                                   4          linear        0.07  0.35  0.18
                                   8          linear        0.11  0.25  0.16
                                   16         linear        0.35  0.27  0.29
                                   32         linear        0.41  0.50  0.31
                conv_recurrent2    16         fft           0.25  0.14  0.20
                                              last          0.18  0.35  0.24
                                              linear        0.26  0.12  0.20
                                              max_time      0.04  0.21  0.02
                                              mean_time     0.07  0.21  0.03
                cornn_model2       16         fft           0.07  0.10  0.02
                                              last          0.07  0.18  0.03
                                              linear        0.04  0.04  0.01
                                              max_time      0.07  0.19  0.02
                                              mean_time     0.07  0.20  0.03
new_tetronimoes baseline1_flexible 2          linear        0.05  0.27  0.13
                                   4          linear        0.11  0.28  0.19
                                   8          linear        0.22  0.11  0.19
                                   16         linear        0.51  0.39  0.33
                                   32         linear        0.47  0.41  0.31
                conv_recurrent2    16         fft           0.07  0.03  0.02
                                              last          0.38  0.24  0.28
                                              linear        0.03  0.02  0.01
                                              max_time      0.31  0.16  0.18
                                              mean_time     0.23  0.15  0.18
                cornn_model2       16         fft           0.01  0.01  0.00
                                              last          0.09  0.03  0.02
                                              linear        0.01  0.01  0.00
                                              max_time      0.15  0.05  0.03
                                              mean_time     0.11  0.04  0.02

                                                           loss_foreground  \
                                                                      mean
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear                  2.44
                                   4          linear                  2.49
                                   8          linear                  1.76
                                   16         linear                  1.73
                                   32         linear                  3.12
                conv_recurrent2    16         fft                     0.93
                                              last                    2.34
                                              linear                  0.78
                                              max_time                1.57
                                              mean_time               1.57
                cornn_model2       16         fft                     0.72
                                              last                    1.34
                                              linear                  0.30
                                              max_time                1.39
                                              mean_time               1.47
new_tetronimoes baseline1_flexible 2          linear                  1.74
                                   4          linear                  1.76
                                   8          linear                  0.70
                                   16         linear                  2.14
                                   32         linear                  2.26
                conv_recurrent2    16         fft                     0.18
                                              last                    1.37
                                              linear                  0.13
                                              max_time                0.99
                                              mean_time               0.95
                cornn_model2       16         fft                     0.07
                                              last                    0.21
                                              linear                  0.05
                                              max_time                0.35
                                              mean_time               0.24


                                                             std
dataset         model_type         num_layers readout_type
mnist           baseline1_flexible 2          linear        0.67
                                   4          linear        0.99
                                   8          linear        0.90
                                   16         linear        1.80
                                   32         linear        1.91
                conv_recurrent2    16         fft           1.23
                                              last          1.38
                                              linear        1.25
                                              max_time      0.13
                                              mean_time     0.22
                cornn_model2       16         fft           0.15
                                              last          0.19
                                              linear        0.07
                                              max_time      0.17
                                              mean_time     0.21
new_tetronimoes baseline1_flexible 2          linear        0.62
                                   4          linear        0.94
                                   8          linear        1.00
                                   16         linear        1.83
                                   32         linear        1.67
                conv_recurrent2    16         fft           0.11
                                              last          1.51
                                              linear        0.05
                                              max_time      0.95
                                              mean_time     0.96
                cornn_model2       16         fft           0.03
                                              last          0.14
                                              linear        0.02
                                              max_time      0.24
                                              mean_time     0.14

In [55]:
datasets = ["mnist", "new_tetronimoes"]
models = ["cornn_model2", "conv_recurrent2", "baseline1_flexible"]
num_layers = [2, 4, 8, 16, 32]
readouts = ["linear", "fft", "last", "mean_time", "max_time"]
readouts = {"linear" : "Linear",
            "fft" : "FFT",
            'last' : 'Last',
            'mean_time' : "Mean",
            "max_time" : "Max"}

In [56]:
dfg1 = grouped_df.loc[grouped_df['dataset'] == 'mnist']
dfg2 = grouped_df.loc[grouped_df['dataset'] == 'new_tetronimoes']

In [57]:
metrics

['acc', 'acc_foreground', 'iou', 'iou_foreground', 'loss', 'loss_foreground']

# Precomputed background-only predictions from results/background_metrics.txt
new_tetronimoes <br>
{'total_iou': 0.7537647857666016, 'total_acc': 0.855583984375} <br>
mnist <br>
{'total_iou': 0.7685087603569031, 'total_acc': 0.8673762226104736} <br>
multi_mnist <br>
{'total_iou': 0.9092979583740234, 'total_acc': 0.95198193359375} <br>

In [58]:
tetro_bg_iou = 0.7537647857666016
tetro_bg_acc = 0.855583984375
mnist_bg_iou = 0.7685087603569031
mnist_bg_acc = 0.8673762226104736

In [63]:
def plot_df(the_df, fpath, bg_iou, bg_acc):
    sns.set_theme()
    metrics = {'acc' : 'Acc',
                'acc_foreground' : 'FG-Acc',
                'iou' : 'IoU',
                'iou_foreground' : 'FG-IoU',
                'loss' : 'Loss',
                'loss_foreground' : 'FG-Loss'}
    models = {'cornn_model2' : "NWM",
              'conv_recurrent2' : "LSTM"}
    orig_metrics = ['acc', 'iou', 'loss', 'acc_foreground', 'iou_foreground', 'loss_foreground']
    fig, axes = plt.subplots(2, 3, figsize=(20, 10))
    count = 0
    for i in range(len(axes)):
        for j in range(len(axes[i])):
        # Sample DataFrame
            metric = orig_metrics[count]
            data = {'Readout': [readouts[readout] for readout in the_df['readout_type'].values],
                    'Model': [models[model] for model in the_df['model_type'].values],
                    'Metric': the_df[metric, 'mean'].values,
                    'STD': the_df[metric, 'std'].values}
            df = pd.DataFrame(data)
            # Pivot the data
            pivot_df = df.pivot(index='Readout', columns='Model', values='Metric')
            pivot_df_std = df.pivot(index='Readout', columns='Model', values='STD')
            pivot_df.plot.barh(grid=True, ax=axes[i][j], xerr=pivot_df_std, legend=False)
            axes[i][j].set_xlabel(metrics[metric], fontsize=16)
            axes[i][j].set_ylabel('Readout', fontsize=16)
            # Plot background
            if metric == 'iou':
                axes[i][j].axvline(x=bg_iou, color='red', linestyle='--')
                axes[i][j].set_xlim(bg_iou - 0.1, 1.0)
            elif metric == 'acc':
                axes[i][j].axvline(x=bg_acc, color='red', linestyle='--')
                axes[i][j].set_xlim(bg_acc - 0.1, 1.0)
            count += 1
            axes[i][j].tick_params(which="both", labelsize=16)


    #plt.legend(loc='best')
    handles, labels = axes[0][0].get_legend_handles_labels()
    fig.legend(handles, labels, fontsize=16)
    fig.tight_layout()
    #plt.show()
    plt.savefig(fpath)
    plt.close()

In [64]:
plot_df(dfg1[5:], "results_scores/bar_mnist.pdf", mnist_bg_iou, mnist_bg_acc)
plot_df(dfg2[5:], "results_scores/bar_tetro.pdf", tetro_bg_iou, tetro_bg_acc)

In [65]:
def plot_df2(the_df, fpath, bg_iou, bg_acc):
    sns.set_theme()
    metrics = {'acc' : 'Acc',
               'acc_foreground' : 'FG-Acc',
                'iou' : 'IoU',
                'iou_foreground' : 'FG-IoU',
                'loss' : 'Loss',
                'loss_foreground' : 'FG-Loss'}
    models = {'cornn_model2' : "NWM",
              'conv_recurrent2' : "LSTM",
              'baseline1_flexible' : "CNN"}
    orig_metrics = ['acc', 'iou', 'loss', 'acc_foreground', 'iou_foreground', 'loss_foreground']
    count = 0
    fig, axes = plt.subplots(2, 3, figsize=(20, 10))
    for count1 in range(len(axes)):
        for count2 in range(len(axes[count1])):
            # Sample DataFrame
            metric = orig_metrics[count]
            layers = []
            the_models = []
            means = []
            stds = []
            for i, model in enumerate(the_df['model_type'].values):
                if model == 'cornn_model2' or model == 'conv_recurrent2':
                    if the_df['readout_type'].values[i] == 'linear':
                        layers.append("Linear")
                        means.append(the_df[metric, 'mean'].values[i])
                        stds.append(the_df[metric, 'std'].values[i])
                        the_models.append(models[the_df['model_type'].values[i]])
                else:
                    layers.append(the_df['num_layers'].values[i])
                    means.append(the_df[metric, 'mean'].values[i])
                    stds.append(the_df[metric, 'std'].values[i])
                    the_models.append(models[the_df['model_type'].values[i]])
                
            data = {
                    'Model': the_models,
                    'Arch' : layers,
                    'Metric': means,
                    'STD': stds,
                    }
            
            df = pd.DataFrame(data)
            # Pivot the data
            pivot_df = df.pivot(index='Model', columns='Arch', values='Metric')
            pivot_df_std = df.pivot(index='Model', columns='Arch', values='STD')
            pivot_df.plot.barh(grid=True, ax=axes[count1][count2], xerr=pivot_df_std, legend=False)
            axes[count1][count2].set_xlabel(metrics[metric], fontsize=16)
            axes[count1][count2].set_ylabel('Model', fontsize=16)
            if metric == 'iou':
                axes[count1][count2].axvline(x=bg_iou, color='red', linestyle='--')
                axes[count1][count2].set_xlim(bg_iou - 0.1, 1.0)
            elif metric == 'acc':
                axes[count1][count2].axvline(x=bg_acc, color='red', linestyle='--')
                axes[count1][count2].set_xlim(bg_acc - 0.1, 1.0)
            axes[count1][count2].tick_params(which="both", labelsize=16)
            
            count += 1


    handles, labels = axes[0][0].get_legend_handles_labels()
    fig.legend(handles, labels, fontsize=16)
    fig.tight_layout()
    #plt.show()
    plt.savefig(fpath)
    plt.close()

In [66]:
plot_df2(dfg1, "results_scores/bar_mnist2.pdf", mnist_bg_iou, mnist_bg_acc)
plot_df2(dfg2, "results_scores/bar_tetro2.pdf", tetro_bg_iou, tetro_bg_acc)