In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Specify the path to your CSV file
#csv_file = 'results/scores_test_multi-mnist.csv'
csv_file = 'results_scores/scores_test_multi-mnist.csv'
df = pd.read_csv(csv_file)
df = df.drop(["run_name"], axis=1)

In [3]:
df.head()

,dataset,model_type,c_mid,extension,loss,iou,acc,loss_foreground,iou_foreground,acc_foreground
0,multi_mnist,cornn_model2,16,1,0.007226,0.995585,0.997769,0.150587,0.925449,0.953455
1,multi_mnist,cornn_model2,16,2,0.007031,0.995760,0.997856,0.146258,0.929140,0.956461
2,multi_mnist,cornn_model2,16,3,0.006659,0.996059,0.998010,0.138133,0.934766,0.960167
3,multi_mnist,cornn_model2,16,5,0.007590,0.995303,0.997626,0.158849,0.920954,0.950927
4,multi_mnist,cornn_model2,16,8,0.006693,0.995981,0.997969,0.139719,0.932644,0.957966

In [4]:
# Define the grouping keys
group_keys = ["dataset", "model_type", "c_mid"]

# Define the metrics for which statistics should be computed
metrics = ["acc", "acc_foreground", "iou", "iou_foreground", "loss", "loss_foreground"]

# Group by the specified keys and compute statistics across the "extension" category
grouped_df = df.groupby(group_keys).agg({
    metric: ['mean', 'std'] for metric in metrics
}).reset_index()

In [5]:
grouped_df

       dataset    model_type c_mid       acc           acc_foreground  \
                                        mean       std           mean
0  multi_mnist  cornn_model2    16  0.997792  0.000289       0.955024
1  multi_mnist         unet2     2  0.983803  0.012942       0.662980
2  multi_mnist         unet2     3  0.995215  0.004677       0.900072
3  multi_mnist         unet2     4  0.998637  0.000237       0.972396
4  multi_mnist         unet2     5  0.998966  0.000187       0.979093

                  iou           iou_foreground                loss            \
        std      mean       std           mean       std      mean       std
0  0.005833  0.995632  0.000571       0.927479  0.009393  0.007236  0.000930
1  0.273073  0.968816  0.024505       0.602172  0.275158  0.057042  0.026632
2  0.104288  0.990648  0.009089       0.865494  0.129080  0.027046  0.012515
3  0.004901  0.997319  0.000464       0.959607  0.006811  0.011345  0.002064
4  0.002979  0.997966  0.000366       0.969339  0.004633  0.007969  0.002252

  loss_foreground
             mean       std
0        0.150571  0.019186
1        1.186565  0.555276
2        0.564322  0.262285
3        0.236330  0.044311
4        0.166124  0.046536

In [6]:
pivoted_df = grouped_df.pivot_table(index=group_keys)#, columns='extension', values=metrics, aggfunc='mean')

/tmp/ipykernel_1285796/3692313265.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  pivoted_df = grouped_df.pivot_table(index=group_keys)#, columns='extension', values=metrics, aggfunc='mean')

In [7]:
pivoted_df

                                     acc           acc_foreground            \
                                    mean       std           mean       std
dataset     model_type   c_mid
multi_mnist cornn_model2 16     0.997792  0.000289       0.955024  0.005833
            unet2        2      0.983803  0.012942       0.662980  0.273073
                         3      0.995215  0.004677       0.900072  0.104288
                         4      0.998637  0.000237       0.972396  0.004901
                         5      0.998966  0.000187       0.979093  0.002979

                                     iou           iou_foreground            \
                                    mean       std           mean       std
dataset     model_type   c_mid
multi_mnist cornn_model2 16     0.995632  0.000571       0.927479  0.009393
            unet2        2      0.968816  0.024505       0.602172  0.275158
                         3      0.990648  0.009089       0.865494  0.129080
                         4      0.997319  0.000464       0.959607  0.006811
                         5      0.997966  0.000366       0.969339  0.004633

                                    loss           loss_foreground
                                    mean       std            mean       std
dataset     model_type   c_mid
multi_mnist cornn_model2 16     0.007236  0.000930        0.150571  0.019186
            unet2        2      0.057042  0.026632        1.186565  0.555276
                         3      0.027046  0.012515        0.564322  0.262285
                         4      0.011345  0.002064        0.236330  0.044311
                         5      0.007969  0.002252        0.166124  0.046536

In [8]:
pivoted_df = pivoted_df.round(2)

In [9]:
pivoted_df

                                 acc       acc_foreground         iou        \
                                mean   std           mean   std  mean   std
dataset     model_type   c_mid
multi_mnist cornn_model2 16     1.00  0.00           0.96  0.01  1.00  0.00
            unet2        2      0.98  0.01           0.66  0.27  0.97  0.02
                         3      1.00  0.00           0.90  0.10  0.99  0.01
                         4      1.00  0.00           0.97  0.00  1.00  0.00
                         5      1.00  0.00           0.98  0.00  1.00  0.00

                               iou_foreground        loss        \
                                         mean   std  mean   std
dataset     model_type   c_mid
multi_mnist cornn_model2 16              0.93  0.01  0.01  0.00
            unet2        2               0.60  0.28  0.06  0.03
                         3               0.87  0.13  0.03  0.01
                         4               0.96  0.01  0.01  0.00
                         5               0.97  0.00  0.01  0.00

                               loss_foreground
                                          mean   std
dataset     model_type   c_mid
multi_mnist cornn_model2 16               0.15  0.02
            unet2        2                1.19  0.56
                         3                0.56  0.26
                         4                0.24  0.04
                         5                0.17  0.05

In [10]:
pivoted_df.to_csv("results_scores/scores_processed_multi-mnist.csv", index=True)
pivoted_df.to_latex("results_scores/scores_processed_multi-mnist", index=True, float_format="%.2f")

# Calculate params

In [11]:
from unet2 import UNet as UNet
from cornn_model2 import Model
from utils import make_model

In [12]:
def calc_params(model):
    # Total number of parameters
    total_params = sum(p.numel() for p in model.parameters())

    # Number of trainable parameters
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return trainable_params, total_params

In [13]:
print(calc_params(UNet(1, 11, c_mid=2)))
print(calc_params(UNet(1, 11, c_mid=3)))
print(calc_params(UNet(1, 11, c_mid=4)))
print(calc_params(UNet(1, 11, c_mid=5)))

(30745, 30745)
(68834, 68834)
(122071, 122071)
(190456, 190456)

In [14]:
net = make_model(device="cuda", model_type="cornn_model2", num_classes=11,
               N=128, dt1=0.1, min_iters=0, max_iters=100, c_in=1, c_mid=16, c_out=16, 
               rnn_kernel=3, img_size=128, kernel_init='op', cell_type="lstm", num_layers=16,
               readout_type="linear_smaller4")
print(calc_params(net))

(54855, 54855)